//'use client'

import './globals.css'
//import './styles.scss'
import type { Metadata } from 'next'
import { Providers } from './providers'
import { Inter } from 'next/font/google'
import Header from './components/header'
//import Navbar from './components/navbar'
//import {NextUIProvider} from '@nextui-org/react'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>
        {/*<script type="text/javascript">
          (function(){
              emailjs.init("YOUR_PUBLIC_KEY");
          })();
        </script>*/}

      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
